fix: remove not important

diff --git a/bin/theme b/bin/theme
--- a/bin/theme
+++ b/bin/theme
@@ -9,36 +9,30 @@ set_alacritty_theme() {
   local conf_file="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty/alacritty.toml"
   [ -f "$conf_file" ] || return
   local theme_file="$HOME/github/alacritty-theme/themes/$1.toml"
-  if [ ! -f "$theme_file" ]; then
-    if [ -t 1 ]; then
-      (cd ~/github/alacritty-theme/themes && fd -Id1 -tf) \
-        | sed 's/\.toml$//' | fzf --preview="sed -i '
-          1c import = [ \"~/github/alacritty-theme/themes/'{}'.toml\" ]' '$conf_file'
-          bat --plain --color=always --no-pager ~/.bashrc"
-      return
-    else
-      echo "alacritty theme not found: $theme_file"
-      ls ~/github/alacritty-theme/themes
-      return 1
-    fi >&2
-  fi
+  [ -f "$theme_file" ] || if [ -t 1 ]; then
+    (cd ~/github/alacritty-theme/themes && fd -Id1 -tf) | sed 's/\.toml$//' | fzf --preview="
+      sed -i '1c import = [ \"~/github/alacritty-theme/themes/'{}'.toml\" ]' ${conf_file@Q}
+      bat --plain --color=always --no-pager ~/.bashrc"
+    return
+  else
+    echo "alacritty theme not found: ${theme_file@Q}"
+    ls ~/github/alacritty-theme/themes
+    return 1
+  fi >&2
   sed -i "1c import = [ \"~${theme_file:${#HOME}}\" ]" "$conf_file"
 }
 
 set_bat_theme() {
   export BAT_THEME=$1
-  local line
-  if bat --list-themes | while read -r line; do
-    [ "$line" != "$1" ] || break
-  done; then
-    if [ -t 1 ]; then
-      # fzf error exits empty
-      BAT_THEME=$(bat --list-themes | fzf --preview='
-        bat --theme {} --plain --color=always --no-pager ~/.bashrc')
-    else
-      echo "bat theme not found: $1" >&2
-      BAT_THEME=''
-    fi
+  bat --list-themes | while read -r line; do
+    [ "$line" = "$2" ] && break
+  done || if [ -t 1 ]; then
+    # fzf error exits empty
+    BAT_THEME=$(bat --list-themes | fzf --preview='
+      bat --theme {} --plain --color=always --no-pager ~/.bashrc')
+  else
+    echo "bat theme not found: ${1@Q}" >&2
+    BAT_THEME=''
   fi
   [ -f ~/.bashrc ] || return
   sed -i "/^export BAT_THEME=/c export BAT_THEME='$BAT_THEME'" ~/.bashrc
@@ -47,19 +41,16 @@ set_bat_theme() {
 set_posh_theme() {
   [ -v POSH_PID ] || return
   local theme_file="$HOME/.config/oh-my-posh/$1.omp.json"
-  if [ ! -f "$theme_file" ]; then
-    if [ -t 1 ]; then
-      theme_file="$HOME/.config/oh-my-posh/$(
-        cd ~/.config/oh-my-posh && fd -Id1 -tf \
-          | sed 's/\.omp\.json$//' | fzf --preview='
-            bat --plain --color=always --no-pager ~/.config/oh-my-posh/{}.omp.json'
-      ).omp.json" || return
-    else
-      echo "posh theme not found: $theme_file"
-      ls ~/.config/oh-my-posh
-      return 1
-    fi >&2
-  fi
+  [ -f "$theme_file" ] || if [ -t 1 ]; then
+    theme_file="$HOME/.config/oh-my-posh/$(
+      cd ~/.config/oh-my-posh && fd -Id1 -tf | sed 's/\.omp\.json$//' | fzf --preview='
+        bat --plain --color=always --no-pager ~/.config/oh-my-posh/{}.omp.json'
+    ).omp.json" || return
+  else
+    echo "posh theme not found: ${theme_file@Q}"
+    ls ~/.config/oh-my-posh
+    return 1
+  fi >&2
   export POSH_THEME=$theme_file
   [ -f ~/.bashrc ] || return
   sed -i "/^\s*export POSH_THEME=/c\  export POSH_THEME=\"\$HOME${theme_file:${#HOME}}\"" ~/.bashrc
@@ -67,28 +58,33 @@ set_posh_theme() {
 
 set_wezterm_theme() {
   [ "$TERM_PROGRAM" = WezTerm ] || return
-  local conf_file cache line
+
+  local conf_file cache line theme=$1
   conf_file="${XDG_CONFIG_HOME:-$HOME/.config}/wezterm/wezterm.lua"
-  if [ ! -f "$conf_file" ]; then
-    [ -f ~/.wezterm.lua ] && conf_file=~/.wezterm.lua || return
-  fi
+  [[ ! -f $conf_file && -f ~/.wezterm.lua ]] && conf_file=~/.wezterm.lua || return
+
   cache="$HOME/.cache/wezterm/themes"
-  if [ ! -f "$cache" ]; then
-    if [ -f ~/github.com/wez/wezterm/docs/colorschemes/data.json ]; then
-      jq -r '.[].metadata.name' < ~/github.com/wez/wezterm/docs/colorschemes/data.json > "$cache"
-    else
-      mkdir -p ~/github.com/wez/wezterm/docs/colorschemes
-      curl -fL https://kkgithub.com/wez/wezterm/raw/docs/colorschemes/data.json \
-        -o ~/github.com/wez/wezterm/docs/colorschemes/data.json || return
-    fi
-  fi
-  if while read -r line; do
-    [ "$line" != "$1" ] || break
-  done < "$cache"; then
-    echo "wezterm theme not valid: $1" >&2
+  [ -f "$cache" ] || if [ -f ~/github.com/wez/wezterm/docs/colorschemes/data.json ]; then
+    jq -r '.[].metadata.name' < ~/github.com/wez/wezterm/docs/colorschemes/data.json > "$cache"
+  else
+    mkdir -p ~/github.com/wez/wezterm/docs/colorschemes
+    curl -fL https://kkgithub.com/wez/wezterm/raw/docs/colorschemes/data.json \
+      -o ~/github.com/wez/wezterm/docs/colorschemes/data.json || return
+  fi || return
+
+  while read -r line; do
+    [ "$line" = "$theme" ] && break
+  done < "$cache" || if [ -t 1 ]; then
+    theme=$(
+      fzf --preview="
+        sed -i '/^config\.color_scheme\s*=/c config.color_scheme = '[[{}]] ${conf_file@Q}
+        bat --plain --color=always --no-pager ~/.bashrc" < "$cache"
+    ) || return
+  else
+    echo "wezterm theme not valid: ${theme@Q}" >&2
     return 1
   fi
-  sed -i "/^config\.color_scheme\s*=/c config.color_scheme = '$1'" "$conf_file"
+  sed -i "/^config\.color_scheme\s*=/c config.color_scheme = '$theme'" "$conf_file"
 }
 
 # $1 ? 'alacritty' | 'bat' | 'posh' | 'wezterm' | 'all'
@@ -98,15 +94,16 @@ set_theme() {
   case "$1" in
     alacritty | bat | posh | wezterm)
       local out
-      out=$(jq '.themes[$name][.theme]=$theme' \
-        --arg name "$1" --arg theme "$2" < "$theme_file") \
-        && tee "$theme_file" > /dev/null <<< "$out"
+      out=$(
+        jq '.themes[$name][.theme]=$theme' \
+          --arg name "$1" --arg theme "$2" < "$theme_file"
+      ) && cat <<< "$out" > "$theme_file"
       "set_${1}_theme" "$2"
       return
       ;;
     all | '') ;;
     *)
-      echo "invalid theme target: $1" >&2
+      echo "invalid theme target: ${1@Q}" >&2
       return 1
       ;;
   esac
@@ -134,17 +131,18 @@ set_theme() {
 
   if out=$(
     jq --arg theme "$theme" 'if .theme == $theme then
-      "all themes already sets to \($theme)" | stderr | empty | halt_error
+      "all themes already set to \($theme)\n" | stderr | empty | halt_error
     else
       .theme = $theme
     end' < "$theme_file"
   ); then
     # change and set each theme
-    out=$(tee "$theme_file" <<< "$out" | jq -r \
-      '.themes as $themes | reduce $ARGS.positional[] as $i
-      (""; . + "set_\($i)_theme \(@sh "\($themes[$i][$theme])")\n")' \
-      --arg theme "$theme" --args bat posh alacritty wezterm) \
-      && eval "$out"
+    out=$(
+      tee "$theme_file" <<< "$out" | jq -r \
+        '.themes as $themes | reduce $ARGS.positional[] as $i
+        (""; . + "set_\($i)_theme \(@sh "\($themes[$i][$theme])")\n")' \
+        --arg theme "$theme" --args bat posh alacritty wezterm
+    ) && eval "$out"
   fi
 }
 
